using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SabreMDT.Services
{
    public class ReportService
    {
        // Placeholder for Base64 logo (Transperent PNG 512x512 recommended)
        private const string LogoBase64 = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIABAl...";

        public string GenerateShiftReport(string officerId, string vehicleId, DateTime signedAt, IEnumerable<dynamic> hits)
        {
            var html = new StringBuilder();
            html.Append("<html><head><style>");
            html.Append("body{font-family:'Segoe UI',Arial;background:#fff;color:#333;margin:40px;}");
            html.Append(".header{border-bottom:3px solid #000;padding-bottom:10px;margin-bottom:20px;}");
            html.Append(".legal-box{background:#f8d7da;border:1px solid #f5c6cb;padding:15px;margin-bottom:20px;font-size:12px;}");
            html.Append("table{width:100%;border-collapse:collapse;margin-top:20px;}");
            html.Append("th,td{padding:12px;border:1px solid #eee;text-align:left;}");
            html.Append("th{background:#000;color:#fff;}");
            html.Append("tr:nth-child(even){background:#fafafa;}");
            html.Append("</style></head><body>");

            // Header with Logo
            html.Append("<div class='header'>");
            html.Append($"<img src='data:image/png;base64,{LogoBase64}' width='80' style='float:right;'/>");
            html.Append("<h1>SABRE ALPR HUB - MISSION REPORT</h1>");
            html.Append($"<p><b>OFFICER:</b> {officerId} | <b>VEHICLE:</b> {vehicleId}</p>");
            html.Append("</div>");

            // Legal Audit Trail
            html.Append("<div class='legal-box'>");
            html.Append($"<b>LEGAL STATUS:</b> Audit Trail Verified. Signed by <b>{officerId}</b> at {signedAt:yyyy-MM-dd HH:mm:ss} UTC.");
            html.Append("</div>");

            html.Append("<table><tr><th>PLATE</th><th>YMMV</th><th>LOCATION / MAPS</th><th>SPEED</th><th>SHA-256 FORENSIC HASH</th></tr>");

            foreach (var hit in hits)
            {
                // Professional Google Maps Search API link
                string mapsLink = $"https://www.google.com/maps/search/?api=1&query={hit.Lat},{hit.Lon}";
                html.Append("<tr>");
                html.Append($"<td><b style='font-size:18px;'>{hit.Plate}</b></td>");
                html.Append($"<td>{hit.Ymmv}</td>");
                html.Append($"<td><a href='{mapsLink}' target='_blank'>{hit.Lat}, {hit.Lon}</a></td>");
                html.Append($"<td>{hit.Speed} KPH</td>");
                html.Append($"<td><code style='font-size:10px;'>{hit.Hash}</code></td>");
                html.Append("</tr>");
            }

            html.Append("</table>");
            html.Append($"<p style='margin-top:40px;color:#888;font-size:12px;'>Generated by Sabre ALPR Hub v2.0 - System UUID: {Guid.NewGuid()}</p>");
            html.Append("</body></html>");

            string fileName = $"Sabre_Report_{officerId}_{DateTime.Now:yyyyMMdd_HHmm}.html";
            string path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), fileName);
            File.WriteAllText(path, html.ToString());
            return path;
        }
    }
}
